### ISSUE TITLE
the model size is same of the initial  and pruning methods

### ISSUE THREAD

**Issue by mk123qwe** [bzantium/pytorch-admm-prunning#2]
the model size is same of the initial  and pruning methods.
in fact ,model's size is not reducing.

**Comment by bzantium** [comment]
That is correct. Based on the paper, this is actually not for reducing the size of the model itself but for making unnecessary weights zero. To efficiently make use of the pruned model, you have to use a specific device designed for such models.

**Comment by mk123qwe** [comment]
> That is correct. Based on the paper, this is actually not for reducing the size of the model itself but for making unnecessary weights zero. To efficiently make use of the pruned model, you have to use a specific device designed for such models.

Some another method channel pruning and filter pruning can ruduce size of model.
This method masks unnecessary weights(but it actually works and is saved as 0 in pth),rather than cut off link.So it makes the model more sparse.Does the device refer to FPGA or ARM?I feel uncertain about this strategy.
